// GenshinCharacters.js
const characters = [
  {
    Name: "Albedo",
    Rarity: "5",
    Element: "Geo",
    Weapon: "Sword",
    Gender: "Male",
  },
  {
    Name: "Alhaitham",
    Rarity: "5",
    Element: "Dendro",
    Weapon: "Sword",
    Gender: "Male",
  },
  {
    Name: "Aloy",
    Rarity: "5",
    Element: "Cryo",
    Weapon: "Bow",
    Gender: "Female",
  },
  {
    Name: "Amber",
    Rarity: "4",
    Element: "Pyro",
    Weapon: "Bow",
    Gender: "Female",
  },
  {
    Name: "Arataki Itto",
    Rarity: "5",
    Element: "Geo",
    Weapon: "Claymore",
    Gender: "Male",
  },
  {
    Name: "Baizhu",
    Rarity: "5",
    Element: "Dendro",
    Weapon: "Catalyst",
    Gender: "Male",
  },
  {
    Name: "Barbara",
    Rarity: "4",
    Element: "Hydro",
    Weapon: "Catalyst",
    Gender: "Female",
  },
  {
    Name: "Beidou",
    Rarity: "4",
    Element: "Electro",
    Weapon: "Claymore",
    Gender: "Female",
  },
  {
    Name: "Bennet",
    Rarity: "4",
    Element: "Pyro",
    Weapon: "Sword",
    Gender: "Male",
  },
  {
    Name: "Candace",
    Rarity: "4",
    Element: "Hydro",
    Weapon: "Polearm",
    Gender: "Female",
  },
  {
    Name: "Charlotte",
    Rarity: "4",
    Element: "Cryo",
    Weapon: "Catalyst",
    Gender: "Female",
  },
  {
    Name: "Chevreuse",
    Rarity: "4",
    Element: "Pyro",
    Weapon: "Polearm",
    Gender: "Female",
  },
  {
    Name: "Chongyun",
    Rarity: "4",
    Element: "Cryo",
    Weapon: "Claymore",
    Gender: "Male",
  },
  {
    Name: "Collei",
    Rarity: "4",
    Element: "Dendro",
    Weapon: "Bow",
    Gender: "Female",
  },
  {
    Name: "Cyno",
    Rarity: "5",
    Element: "Electro",
    Weapon: "Polearm",
    Gender: "Male",
  },
  {
    Name: "Dehya",
    Rarity: "5",
    Element: "Pyro",
    Weapon: "Claymore",
    Gender: "Female",
  },
  {
    Name: "Diluc",
    Rarity: "5",
    Element: "Pyro",
    Weapon: "Claymore",
    Gender: "Male",
  },
  {
    Name: "Diona",
    Rarity: "4",
    Element: "Cryo",
    Weapon: "Bow",
    Gender: "Female",
  },
  {
    Name: "Dori",
    Rarity: "4",
    Element: "Electro",
    Weapon: "Claymore",
    Gender: "Female",
  },
  {
    Name: "Eula",
    Rarity: "5",
    Element: "Cryo",
    Weapon: "Claymore",
    Gender: "Female",
  },
  {
    Name: "Faruzan",
    Rarity: "4",
    Element: "Anemo",
    Weapon: "Bow",
    Gender: "Female",
  },
  {
    Name: "Fischl",
    Rarity: "4",
    Element: "Electro",
    Weapon: "Bow",
    Gender: "Female",
  },
  {
    Name: "Freminet",
    Rarity: "4",
    Element: "Cryo",
    Weapon: "Claymore",
    Gender: "Male",
  },
  {
    Name: "Furina",
    Rarity: "5",
    Element: "Hydro",
    Weapon: "Sword",
    Gender: "Female",
  },
  {
    Name: "Gaming",
    Rarity: "4",
    Element: "Pyro",
    Weapon: "Claymore",
    Gender: "Male",
  },
  {
    Name: "Ganyu",
    Rarity: "5",
    Element: "Cryo",
    Weapon: "Bow",
    Gender: "Female",
  },
  {
    Name: "Gorou",
    Rarity: "4",
    Element: "Geo",
    Weapon: "Bow",
    Gender: "Male",
  },
  {
    Name: "Hutao",
    Rarity: "5",
    Element: "Pyro",
    Weapon: "Polearm",
    Gender: "Female",
  },
  {
    Name: "Jean",
    Rarity: "5",
    Element: "Anemo",
    Weapon: "Sword",
    Gender: "Female",
  },
  {
    Name: "Kaedehara Kazuha",
    Rarity: "5",
    Element: "Anemo",
    Weapon: "Sword",
    Gender: "Male",
  },
  {
    Name: "Kaeya",
    Rarity: "4",
    Element: "Cryo",
    Weapon: "Sword",
    Gender: "Male",
  },
  {
    Name: "Kamisato Ayaka",
    Rarity: "5",
    Element: "Cryo",
    Weapon: "Sword",
    Gender: "Female",
  },
  {
    Name: "Kamisato Ayato",
    Rarity: "5",
    Element: "Hydro",
    Weapon: "Sword",
    Gender: "Male",
  },
  {
    Name: "Kaveh",
    Rarity: "4",
    Element: "Dendro",
    Weapon: "Claymore",
    Gender: "Male",
  },
  {
    Name: "Keqing",
    Rarity: "5",
    Element: "Electro",
    Weapon: "Sword",
    Gender: "Female",
  },
  {
    Name: "Kirara",
    Rarity: "4",
    Element: "Dendro",
    Weapon: "Sword",
    Gender: "Male",
  },
  {
    Name: "Klee",
    Rarity: "5",
    Element: "Pyro",
    Weapon: "Catalyst",
    Gender: "Female",
  },
  {
    Name: "Kujou Sara",
    Rarity: "4",
    Element: "Electro",
    Weapon: "Bow",
    Gender: "Female",
  },
  {
    Name: "Kuki Shinobu",
    Rarity: "4",
    Element: "Electro",
    Weapon: "Sword",
    Gender: "Female",
  },
  {
    Name: "Layla",
    Rarity: "4",
    Element: "Cryo",
    Weapon: "Sword",
    Gender: "Female",
  },
  {
    Name: "Lisa",
    Rarity: "4",
    Element: "Electro",
    Weapon: "Catalyst",
    Gender: "Female",
  },
  {
    Name: "Lynette",
    Rarity: "4",
    Element: "Anemo",
    Weapon: "Sword",
    Gender: "Female",
  },
  {
    Name: "Lyney",
    Rarity: "5",
    Element: "Pyro",
    Weapon: "Bow",
    Gender: "Female",
  },
  {
    Name: "Mika",
    Rarity: "4",
    Element: "Cryo",
    Weapon: "Polearm",
    Gender: "Female",
  },
  {
    Name: "Mona",
    Rarity: "5",
    Element: "Hydro",
    Weapon: "Catalyst",
    Gender: "Female",
  },
  {
    Name: "Nahida",
    Rarity: "5",
    Element: "Dendro",
    Weapon: "Catalyst",
    Gender: "Female",
  },
  {
    Name: "Navia",
    Rarity: "5",
    Element: "Geo",
    Weapon: "Claymore",
    Gender: "Female",
  },
  {
    Name: "Neuvillette",
    Rarity: "5",
    Element: "Hydro",
    Weapon: "Catalyst",
    Gender: "Male",
  },
  {
    Name: "Nilou",
    Rarity: "5",
    Element: "Hydro",
    Weapon: "Sword",
    Gender: "Female",
  },
  {
    Name: "Ningguang",
    Rarity: "4",
    Element: "Geo",
    Weapon: "Catalyst",
    Gender: "Female",
  },
  {
    Name: "Noelle",
    Rarity: "4",
    Element: "Geo",
    Weapon: "Claymore",
    Gender: "Female",
  },
  {
    Name: "Qiqi",
    Rarity: "5",
    Element: "Cryo",
    Weapon: "Sword",
    Gender: "Female",
  },
  {
    Name: "Raiden Shogun",
    Rarity: "5",
    Element: "Electro",
    Weapon: "Polearm",
    Gender: "Female",
  },
  {
    Name: "Razor",
    Rarity: "4",
    Element: "Electro",
    Weapon: "Claymore",
    Gender: "Male",
  },
  {
    Name: "Rosaria",
    Rarity: "4",
    Element: "Cryo",
    Weapon: "Polearm",
    Gender: "Female",
  },
  {
    Name: "Sanganomiya Kokomi",
    Rarity: "5",
    Element: "Hydro",
    Weapon: "Catalyst",
    Gender: "Female",
  },
  {
    Name: "Sayu",
    Rarity: "4",
    Element: "Anemo",
    Weapon: "Claymore",
    Gender: "Female",
  },
  {
    Name: "Shenhe",
    Rarity: "5",
    Element: "Cryo",
    Weapon: "Polearm",
    Gender: "Female",
  },
  {
    Name: "Shikanoin Heizou",
    Rarity: "4",
    Element: "Anemo",
    Weapon: "Catalyst",
    Gender: "Male",
  },
  {
    Name: "Sucrose",
    Rarity: "4",
    Element: "Anemo",
    Weapon: "Catalyst",
    Gender: "Female",
  },
  {
    Name: "Tartaglia",
    Rarity: "5",
    Element: "Hydro",
    Weapon: "Bow",
    Gender: "Male",
  },
  {
    Name: "Thoma",
    Rarity: "4",
    Element: "Pyro",
    Weapon: "Polearm",
    Gender: "Male",
  },
  {
    Name: "Tighnari",
    Rarity: "5",
    Element: "Dendro",
    Weapon: "Bow",
    Gender: "Male",
  },
  {
    Name: "Traveler Female",
    Rarity: "5",
    Element: "Anemo",
    Weapon: "Sword",
    Gender: "Female",
  },
  {
    Name: "Traveler Male",
    Rarity: "5",
    Element: "Anemo",
    Weapon: "Sword",
    Gender: "Male",
  },
  {
    Name: "Venti",
    Rarity: "5",
    Element: "Anemo",
    Weapon: "Bow",
    Gender: "Male",
  },
  {
    Name: "Wanderer",
    Rarity: "5",
    Element: "Anemo",
    Weapon: "Catalyst",
    Gender: "Male",
  },
  {
    Name: "Wriothesley",
    Rarity: "5",
    Element: "Cryo",
    Weapon: "Catalyst",
    Gender: "Male",
  },
  {
    Name: "Xiangling",
    Rarity: "4",
    Element: "Pyro",
    Weapon: "Polearm",
    Gender: "Female",
  },
  {
    Name: "Xianyun",
    Rarity: "5",
    Element: "Anemo",
    Weapon: "Catalyst",
    Gender: "Female",
  },
  {
    Name: "Xiao",
    Rarity: "5",
    Element: "Anemo",
    Weapon: "Polearm",
    Gender: "Male",
  },
  {
    Name: "Xingqiu",
    Rarity: "4",
    Element: "Hydro",
    Weapon: "Sword",
    Gender: "Male",
  },
  {
    Name: "Xinyan",
    Rarity: "4",
    Element: "Pyro",
    Weapon: "Claymore",
    Gender: "Female",
  },
  {
    Name: "Yae Miko",
    Rarity: "5",
    Element: "Electro",
    Weapon: "Catalyst",
    Gender: "Female",
  },
  {
    Name: "Yanfei",
    Rarity: "4",
    Element: "Pyro",
    Weapon: "Catalyst",
    Gender: "Female",
  },
  {
    Name: "Yaoyao",
    Rarity: "4",
    Element: "Electro",
    Weapon: "Polearm",
    Gender: "Female",
  },
  {
    Name: "Yelan",
    Rarity: "5",
    Element: "Hydro",
    Weapon: "Bow",
    Gender: "Female",
  },
  {
    Name: "Yoimiya",
    Rarity: "5",
    Element: "Pyro",
    Weapon: "Bow",
    Gender: "Female",
  },
  {
    Name: "Yunjin",
    Rarity: "4",
    Element: "Geo",
    Weapon: "Polearm",
    Gender: "Female",
  },
  {
    Name: "Zhongli",
    Rarity: "5",
    Element: "Geo",
    Weapon: "Polearm",
    Gender: "Male",
  },
];

export default characters;
